-- AlterTable
ALTER TABLE "Admin" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "TicketDetail" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "TicketHeader" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
